CREATE DATABASE acme_net;

CREATE TABLE locked_cards (ID INTEGER NOT NULL PRIMARY KEY,
pan CHAR(16) NOT NULL,
reason CHAR(3) NOT NULL, 
comment VARCHAR
);

CREATE SEQUENCE hibernate_sequence;

DO $$
BEGIN
  CREATE USER  acme WITH PASSWORD 'acme' CREATEDB;
  EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'not creating role acme -- it already exists';
END
$$;

GRANT ALL PRIVILEGES ON DATABASE acme_net TO PUBLIC;
GRANT ALL PRIVILEGES ON TABLE locked_cards TO acme;
GRANT ALL PRIVILEGES ON SEQUENCE hibernate_sequence TO acme;
	
