apiVersion: v1
kind: Service
metadata:
  name: acme-bank-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  - port: 8082
    targetPort: 8082
    name: management
  selector:
    app: acme-bank-app